spring:
  profiles:
#    active: dev
    active: test
#    active: pro
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    pool: 
      max-idle: 200
      min-idle: 200
      max-active: 2000
      max-wait: 1000


http: 
  maxTotal: 100 #最大连接数
  defaultMaxPerRoute: 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  validateAfterInactivity: 1000
